language: node_js
node_js:
   - "4.0"
   - "4.1"
   - "4.2"
   - "4.3"
   - "4.4"
   - "5"
   - "5.1"
addons:
  apt:
    packages:
      - make
script: make release
deploy:
  provider: releases
  api_key:
    secure: X6CtPnWhsVM/1mMMrU0Da45ny/b9uPbW1LeC+6v97LEMH9DGRwnCYe4l7/YIInjIgVFHDhIbalZUze3nQfokDABQ7HatJ9g7mVghTHODT8shavJ00l3amDKCyPelh+kcAGmPayIEqpr+QARkuBLYkTXSOidaqTHBBxbMsOdfRzU=
  file: strichliste-web.tar.gz
  on:
    tags: true
    node: "4.4"
    branch: master
    repo: hackerspace-bootstrap/strichliste-web
